// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqfZuOosx74jCu1pSaAHV2AuAY0i45pHc',
    appId: '1:642353294475:web:2dd49b5687c39b6ae0788e',
    messagingSenderId: '642353294475',
    projectId: 'movie-watch-69af5',
    authDomain: 'movie-watch-69af5.firebaseapp.com',
    storageBucket: 'movie-watch-69af5.firebasestorage.app',
    measurementId: 'G-4Q6QQVPCH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ3XvzEgkHdi1iB7uUrjXvxPwrYwg1Lvs',
    appId: '1:642353294475:android:b0d9495af3d8919de0788e',
    messagingSenderId: '642353294475',
    projectId: 'movie-watch-69af5',
    storageBucket: 'movie-watch-69af5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAviFUdPAQrO0R93J1V3oopZEWUnVFsi0w',
    appId: '1:642353294475:ios:4275ff97ad3b4c6fe0788e',
    messagingSenderId: '642353294475',
    projectId: 'movie-watch-69af5',
    storageBucket: 'movie-watch-69af5.firebasestorage.app',
    androidClientId: '642353294475-ero0a8e60n79ce1fh7drdilgp8gum1us.apps.googleusercontent.com',
    iosClientId: '642353294475-eikh06sc0qfnemfmibfl739rmrg7sq70.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAviFUdPAQrO0R93J1V3oopZEWUnVFsi0w',
    appId: '1:642353294475:ios:4275ff97ad3b4c6fe0788e',
    messagingSenderId: '642353294475',
    projectId: 'movie-watch-69af5',
    storageBucket: 'movie-watch-69af5.firebasestorage.app',
    androidClientId: '642353294475-ero0a8e60n79ce1fh7drdilgp8gum1us.apps.googleusercontent.com',
    iosClientId: '642353294475-eikh06sc0qfnemfmibfl739rmrg7sq70.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieWatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqfZuOosx74jCu1pSaAHV2AuAY0i45pHc',
    appId: '1:642353294475:web:4a685b23f7c05c14e0788e',
    messagingSenderId: '642353294475',
    projectId: 'movie-watch-69af5',
    authDomain: 'movie-watch-69af5.firebaseapp.com',
    storageBucket: 'movie-watch-69af5.firebasestorage.app',
    measurementId: 'G-J6G1BKVEN5',
  );

}